name: CI

on: [ workflow_dispatch ]

jobs:
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    env:
      CC: clang-15
      CXX: clang++-15
      BUILD_TYPE: Release
    steps:
      - name: Install new clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm-snapshot.asc
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
          sudo apt-get update -qq
          sudo apt-get install -yq clang-15
        shell: bash
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/install-from-git
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
